version: "3.4"

services:
  muse:
    image: soulwax/echoblossom:latest
    build: .
    volumes:
      - ./muse:/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - BOT_STATUS=${BOT_STATUS}
      - CACHE_LIMIT=${CACHE_LIMIT}
      - BOT_ACTIVITY_TYPE=${BOT_ACTIVITY_TYPE}
      - BOT_ACTIVITY_URL=${BOT_ACTIVITY_URL}
      - BOT_ACTIVITY=${BOT_ACTIVITY}
      - ECHOELYSIUM_STREAMING_URL=${ECHOELYSIUM_STREAMING_URL}
      - ECHOELYSIUM_STREAMING_KEY=${ECHOELYSIUM_STREAMING_KEY}
      - ECHOELYSIUM_STREAMING_SECRET=${ECHOELYSIUM_STREAMING_SECRET}
      - PREFER_ECHOELYSIUM=${PREFER_ECHOELYSIUM}
      - FALLBACK_YOUTUBE=${FALLBACK_YOUTUBE}
      - DOWNLOAD_URL=${DOWNLOAD_URL}
      - DOWNLOAD_KEY=${DOWNLOAD_KEY}
    restart: always
